### ISSUE TITLE
Login and database connection

### ISSUE THREAD

**Issue by j-mendez** [FullSailWDD/Pro-Leet-Peeps#1]
Need to get login working with passport so the user can be identified.

**Comment by reactivepixel** [comment]
Here is [an app](https://github.com/reactivepixel/concourse/blob/master/app.js) that successfully utilizes Passport.

Additionally Scotch.io has a [great tutorial](https://scotch.io/tutorials/easy-node-authentication-setup-and-local) on using passport with node.

**Comment by j-mendez** [comment]
Thanks.
